### ISSUE TITLE
Update imports to fsnotify

### ISSUE THREAD

**Issue by barkimedes** [ivpusic/rerun#13]
In your `watcher.go` and `watcher_test.go` files, can you update the imports from `"gopkg.in/fsnotify.v1"` to `"gopkg.in/fsnotify/fsnotify.v1"`?

See https://github.com/go-fsnotify/fsnotify/issues/1

(`go get github.com/ivpusic/rerun` is broken because of this)

thanks!

**Comment by ivpusic** [comment]
tnx for a warning about this. Could you send a PR for this?

**Comment by guineveresaenger** [comment]
there's a patch on v0.19.1 I believe

**Comment by barkimedes** [comment]
sorry, probably should have closed this years ago...
