### ISSUE TITLE
Allow rebuilds also based on attribute changes

### ISSUE THREAD

**Issue by jalkanen** [ivpusic/rerun#8]
If you use Vagrant, you can use https://github.com/mhallin/vagrant-notify-forwarder will send notifications from the host to the guest. However, it sends all changes only as ATTRIB changes, as per https://github.com/mhallin/notify-forwarder/issues/2.  These are visible to fsnotify as "fsnotify.Chmod" changes.

However, rerun filters out the fsnotify.Chmod as a "non-interesting" changes, and therefore does not properly trigger a rebuild.  While most Chmod changes aren't useful, having a config option that also listens to them would be useful for Vagrant users.

The following diff should illustrate what I mean, though it's obviously missing the config option.

```
diff --git a/watcher.go b/watcher.go
index 44c3db2..297d792 100644
--- a/watcher.go
+++ b/watcher.go
@@ -25,7 +25,7 @@ func (w *watcher) isEventImportant(ev fsnotify.Event) bool {
                return false
        }
 
-       importantEvent := ev.Op == fsnotify.Write || ev.Op == fsnotify.Rename || ev.Op == fsnotify.Remove
+       importantEvent := ev.Op == fsnotify.Write || ev.Op == fsnotify.Rename || ev.Op == fsnotify.Remove || ev.Op == fsnotify.Chmod
        if !importantEvent {
                return false
        }

```

**Comment by ivpusic** [comment]
sounds reasonable. do you have a time to make pull request for this feature? So we will need to update config struct, and conditionally listen for ChMood, and write some test (https://github.com/ivpusic/rerun/blob/master/watcher_test.go) to check if this works.

**Comment by jalkanen** [comment]
There you go :-) https://github.com/ivpusic/rerun/pull/9
